# Generated by Django 2.2.12 on 2021-07-03 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='titel',
            new_name='title',
        ),
    ]
